name=MQTT_OTA
version=3.2.0
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=A lightweight MQTT-based Over-The-Air (OTA) update firmware library for ESP32, ESP8266 or other that MQTT connectivity support.
paragraph=Designed for edge computing and industrial monitoring, this library allows ESP microcontrollers to receive OTA firmware updates via MQTT. It utilizes Dependency Injection by reusing an existing PubSubClient connection, maximizing RAM efficiency and avoiding duplicate MQTT client sessions. Features chunked payload handling, MD5 validation, and timeout protection.
category=Communication
url=https://github.com/0ADILL3/MQTT_OTA
architectures=esp32
depends=PubSubClient,Preferences
includes=MQTT_OTA.h